project:
  type: book
  output-dir: docs

execute:
  freeze: auto

lang: pt 

book:
  title: "Dados e Indicadores de Interesse para a Saúde Pública"
  author: "Raphael de Freitas Saldanha"
  date: 2026-04-30
  search: true
  # downloads: [pdf, epub]
  google-analytics: 
    tracking-id: G-2M7VLSRDCB
    anonymize-ip: false
  chapters:
    - index.qmd
    - intro.qmd
    - indi.qmd
    - harmo.qmd
    - selecao.qmd
    - qualidade.qmd
    - incerteza.qmd
    - socio.qmd # Sociodemográficos
    - saude.qmd # Saúde
    - ambi.qmd  # Ambientais (cobertura e uso do solo)
    - clima.qmd # Climáticos e atmosféricos
    - inter.qmd # Dados da internet e redes sociais
    - etica.qmd # Ética e governança
    - reproducibilidade.qmd
    - estudo_caso.qmd
    - referencias.qmd
  appendices:
    - glossario.qmd
    - checklist.qmd

bibliography: references.bib
csl: abnt.csl

format:
  html:
    theme:
      light: journal
      dark: darkly
  #pdf:
  #  documentclass: scrreprt
  #epub: 
  #  toc: true
